name: CI

on:
  push:
  pull_request:

jobs:
  flake8-job:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    name: Flake8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
             pytest -sv

      - name: Run flake8
        run: |
            flake8 --config flake8-start-config .
