name: CI

on: [push, pull_request]

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Flake8
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run flake8
        run: |
            flake8 .
