name: CI

on:
  push:
  pull_request:

jobs:
  flake8-job:

    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0-rc.2"]

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Python ${{matrix.python-version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      #- name: Install deps
      #  run: |
      #    pip install -r requirements.txt
      #    pip install pytest

      - name: Run tests
        run: |
            pytest -sv

      - name: Run flake8
        run: |
            flake8 --config flake8-start-config .
